export const FETCH_POSTS_DATA = "FETCH_POSTS_DATA"
export const DELETE_POST = "DELETE_POST"
export const ADD_POST = "ADD_POST"
export const ON_EDIT_POST = "ON_EDIT_POST"
export const OPEN_POST_FORM = "OPEN_POST_POST"
export const CLOSE_POST_FORM = "CLOSE_POST_POST"